CREATE TABLE cities(
id	INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(200),
STATUS BOOLEAN
);

CREATE TABLE jobsj(
id INT INCREMENT PRIMARY KEY,
NAME VARCHARCHAR(200),
STATUS BOOLEAN
);

CREATE TABLE employees(
id INT auto_INCREMENT PRIMARY KEY,
NAME VARCHAR(200),
ciudad_id INT,
jobs_id INT,
salary DOUBLE,
STATUS BOOLEAN DEFAULT 1,
FOREIGN KEY (ciudad_id)REFERENCES cities(id),
FOREIGN KEY (jobs_id)REFERENCES jobsj(id)
);
